### ISSUE TITLE
old version of faraday in gemspec

### ISSUE THREAD

**Issue by edk** [coupa/sand-ruby#17]
it seems https://github.com/coupa/sand-ruby/blob/master/sand.gemspec#L27 ties us to faraday 0.9.0 and latest is current 0.15.2

Not critical yet, but because a number of other gems rely on faraday, this may cause us problems at some point in the future, since it makes other dependent gems stuck at fixed versions.

**Comment by johnwu96822** [comment]
I've changed the faraday dependency to >= 0.9.0
