### ISSUE TITLE
Enhancement Request: Add a `timeout` option to `request` and `check_request`

### ISSUE THREAD

**Issue by karl-sundequist-blomdahl** [coupa/sand-ruby#26]
Today the `sand-ruby` gem uses the default faraday client (though `oauth2`) which has a _default_ connection and read timeout of `60` seconds (or can be infinite depending on OS configurations). This can be a very long time for the caller to wait, so it would be desirable to be able to specify a connection and read timeout as part of the options when calling `sand-ruby`.

## Suggested API

I suggest we add two optional keys to the `options` hash that can be passed to `request` and `check_request`:

- `options[:timeout]` The read timeout in seconds, if empty uses the default of the HTTP backend implementation.
- `options[:open_timeout]` The connection timeout in seconds, if empty uses the default of the HTTP backend implementation.

Alternatively consolidate them into one `timeout` option.

## Suggested API usage example

```ruby
Coupa::Sand.request(num_retry: 1, timeout: 3, open_timeout: 3) do |access_token|
  ...
end
```

**Comment by stephane-pelchat** [comment]
@johnny-lai @johnwu96822 let's work on this sand client side timeout asap, thanks @karl-sundequist-blomdahl  for the writeup

**Comment by karl-sundequist-blomdahl** [comment]
If we could agree on an API early during development that would be great, since we could ship our code with those options early and since unused `options` parameters passed to `request` are ignored there would be no negative side-effects.

This would allowing us to ship faster and in parallel.

**Comment by johnwu96822** [comment]
https://coupadev.atlassian.net/browse/CD-244080

**Comment by johnwu96822** [comment]
CD-244080

**Comment by johnwu96822** [comment]
The `timeout` and `open_timeout` options can be stored with the client/service objects and can also be passed in as overwrite options in `request` and `check_request` methods.
